apiVersion: v1
kind: Service
metadata:
  name: jenkins-web
  namespace: jenkins-second
spec:
  type: NodePort
  selector:
    app: jenkins          # ← то же самое: нужен отступ (2 пробела) перед app
  ports:
    - name: web
      port: 8080
      targetPort: 8080
      nodePort: 32001